from __future__ import annotations

import re
from typing import Mapping

import pandas as pd

from schema import AGENT_LOGIN_PATTERNS, AGENT_NAMES


def _value(row: Mapping[str, object], *names: str) -> str:
    for name in names:
        value = row.get(name)
        if value is not None:
            return str(value)
    return ""


def is_agent_authored(row: Mapping[str, object]) -> bool:
    """Return True if a PR row matches the shared AIDev-style agent heuristic."""
    explicit = _value(row, "is_agent", "is_agentic", "agentic", "agent")
    if explicit.lower() in {"true", "1", "yes", "y"}:
        return True
    if explicit.lower() in {"false", "0", "no", "n", "none", "nan"}:
        return False

    agent_name = _value(row, "agent", "agent_name", "author_agent", "label").lower()
    if any(name in agent_name for name in AGENT_NAMES):
        return True

    login = _value(row, "user", "login", "author", "author_login", "user_login").lower()
    user_type = _value(row, "user_type", "author_type", "type").lower()
    if user_type == "bot" and any(pattern in login for pattern in AGENT_LOGIN_PATTERNS):
        return True

    body = _value(row, "body", "description").lower()
    title = _value(row, "title").lower()
    text = f"{title}\n{body}"
    agent_markers = (
        r"generated with \[claude code\]",
        r"co-authored-by:\s*claude",
        r"generated by (openai )?codex",
        r"created by (github )?copilot",
        r"de?vin ai",
        r"cursor agent",
    )
    return any(re.search(marker, text) for marker in agent_markers)


def keep_agent_arm(row: Mapping[str, object]) -> bool:
    return is_agent_authored(row)


def keep_human_arm(row: Mapping[str, object]) -> bool:
    return not is_agent_authored(row)


def filter_by_author_with_details(
    df: pd.DataFrame,
    arm: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    predicate = keep_agent_arm if arm == "agent" else keep_human_arm
    if df.empty:
        return df.copy(), df.copy()
    mask = df.apply(lambda row: predicate(row.to_dict()), axis=1)
    return df.loc[mask].copy(), df.loc[~mask].copy()
